version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn service.server:app --reload --host 0.0.0.0 --port 8000
    restart: always
    tty: true
    volumes:
      - .:/application
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.21.3
    restart: always
    tty: true
    ports:
      - "8990:8000"
    environment:
      URL: http://web:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "web"
